config/routes.rb
Rails.application.routes.draw do
  # Routes handled by Rails
  resource :session do
    get :signin, to: "sessions#new"
  end

  resource :registration do
    get "/", to: "registrations#new"
  end

  resources :passwords, param: :token
  resources :organisations, only: %i[ show edit index update ] do
    resource :membership, only: [] do
      patch :quit
    end
  end
  resources :users, only: %i[ edit update show ]

  # API routes for React frontend
  namespace :api do
    resources :organisations, only: [] do
      resources :posts
    end
  end

  # Routes handles by React
  get "organisations/:organisation_id/posts", to: "react#index"
  get "organisations/:organisation_id/posts/:id", to: "react#index"
  get "organisations/:organisation_id/posts/new", to: "react#index"
  get "organisations/:organisation_id/posts/:id/edit", to: "react#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Root path ("/")
  root to: redirect("/session/signin")
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Organisation Hub" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>

    <%= vite_stylesheet_tag 'application.css' %>
  </head>

  
  <body>
    
    
    <header>
    <% if authenticated? %>
    <nav class="w-full bg-white px-4 py-3 flex justify-normal items-center shadow-2xl border-b border-gray-300">
      <div class="flex justify-normal items-center w-full">
          <%= link_to "Home", organisations_path, class: "text-gray-700 hover:text-indigo-600" %>
          <%= link_to "Profile", user_path(Current.user), class: "text-gray-700 hover:text-indigo-600 mx-4" %>
          <div class="text-gray-700 hover:text-red-600">
          <%= button_to "Log out", session_path, method: :delete %>
          </div>
      </div>
      
    </nav>
    <% end %> 
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>